import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bill Splitter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
        <code className="bg-black flex text-pink-700 font-light flex-col text-center">
          @frontendmentor Challenge
          <code className="font-light">Developed by <a className="text-yellow-500 drop-shadow-md" href="github.com/Darkx-dev">Roshan</a></code>
        </code>
      </body>
    </html>
  );
}
